[package]
name = "cargo-cage"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
openssl = { version = "0.10", features = ["vendored"] }
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
thiserror = "1"
